### ISSUE TITLE
I don't even know anymore

### ISSUE THREAD

**Issue by ControlCplusControlV** [ControlCplusControlV/Golem-Image-Classifier#12]
```2021-07-31T07:54:47.300-0700 WARNING yapapi.services] Unhandled exception in service
Traceback (most recent call last):
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/services.py", line 469, in _run_instance
    batch = batch_task.result()
  File "/home/controlc/Downloads/gimg5/requestor.py", line 62, in start
    service = yield self._ctx.commit()
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/services.py", line 478, in _run_instance
    fut_result = yield batch
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/engine.py", line 556, in process_batches
    results = await get_batch_results()
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/engine.py", line 542, in get_batch_results
    raise CommandExecutionError(evt.command, evt.message, evt.stderr)
yapapi.rest.activity.CommandExecutionError: Command '{'run': {'entry_point': '/bin/sh', 'args': ('-c', '/golem/run/ImageClassification.py', '&'), 'capture': {'stdout': {'stream': {}}, 'stderr': {'stream': {}}}}}' failed on provider; message: 'ExeScript command exited with code 2'; stderr: '/golem/run/ImageClassification.py: 1: /golem/run/ImageClassification.py: import: not found
/golem/run/ImageClassification.py: 2: /golem/run/ImageClassification.py: import: not found
/golem/run/ImageClassification.py: 3: /golem/run/ImageClassification.py: from: not found
/golem/run/ImageClassification.py: 4: /golem/run/ImageClassification.py: from: not found
/golem/run/ImageClassification.py: 5: /golem/run/ImageClassification.py: from: not found
/golem/run/ImageClassification.py: 6: /golem/run/ImageClassification.py: from: not found
/golem/run/ImageClassification.py: 7: /golem/run/ImageClassification.py: from: not found
/golem/run/ImageClassification.py: 8: /golem/run/ImageClassification.py: from: not found
/golem/run/ImageClassification.py: 9: /golem/run/ImageClassification.py: from: not found
/golem/run/ImageClassification.py: 10: /golem/run/ImageClassification.py: from: not found
/golem/run/ImageClassification.py: 11: /golem/run/ImageClassification.py: from: not found
/golem/run/ImageClassification.py: 12: /golem/run/ImageClassification.py: from: not found
/golem/run/ImageClassification.py: 13: /golem/run/ImageClassification.py: from: not found
/golem/run/ImageClassification.py: 14: /golem/run/ImageClassification.py: import: not found
/golem/run/ImageClassification.py: 15: /golem/run/ImageClassification.py: import: not found
/golem/run/ImageClassification.py: 16: /golem/run/ImageClassification.py: import: not found
/golem/run/ImageClassification.py: 17: /golem/run/ImageClassification.py: import: not found
/golem/run/ImageClassification.py: 18: /golem/run/ImageClassification.py: from: not found
/golem/run/ImageClassification.py: 19: /golem/run/ImageClassification.py: from: not found
/golem/run/ImageClassification.py: 20: /golem/run/ImageClassification.py: train_path: not found
/golem/run/ImageClassification.py: 21: /golem/run/ImageClassification.py: valid_path: not found
/golem/run/ImageClassification.py: 22: /golem/run/ImageClassification.py: test_path: not found
/golem/run/ImageClassification.py: 23: /golem/run/ImageClassification.py: Syntax error: "(" unexpected
```

**Comment by ControlCplusControlV** [comment]
```
import numpy as np
import keras
from keras import backend as k
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense, Flatten
from keras.applications import vgg16
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import *
from sklearn.metrics import confusion_matrix
import itertools
import os
import argparse
import rpyc
from rpyc.utils.server import ThreadedServer
from threading import Thread
train_path = 'cats-dogs-monkeys-cows/train'
valid_path = 'cats-dogs-monkeys-cows/valid'
test_path = 'cats-dogs-monkeys-cows/test'
class ClassifierService(rpyc.Service):
    def exposed_buildModel(self,train_path, valid_path, classes):
        train_batches = ImageDataGenerator().flow_from_directory(train_path, target_size=(224,224), classes=classes, batch_size=10)
        valid_batches = ImageDataGenerator().flow_from_directory(valid_path, target_size=(224,224), classes=classes, batch_size=4)

        imgs, labels = next(train_batches)

        train_batches.class_indices

        vgg16_model = keras.applications.vgg16.VGG16(weights="/golem/work/vgg16.h5")

        model = Sequential()
        for i in vgg16_model.layers:
            model.add(i)
        model.layers.pop()
        for layer in model.layers:
            layer.trainable = False
        model.add(Dense(4, activation='softmax'))
        model.compile(Adam(lr=0.07), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit_generator(train_batches, steps_per_epoch=1,validation_data=valid_batches, validation_steps=1, epochs=30, verbose=2)
        server.fmodel = model
        return True
    def exposed_predict(self, classes, testloc):
        model = server.fmodel
        test_batches = ImageDataGenerator().flow_from_directory(testloc, target_size=(224,224), classes=["Unknown"], batch_size=1,save_format='jpg')
        test_imgs, test_labels = next(test_batches)
        predictions = model.predict_on_batch(np.array(test_imgs))
        test_labels = np.array(test_labels.argmax(axis=1))
        predictions = np.array(predictions.argmax(axis=1))
        #print(test_labels) Ignored because its wrong
        return predictions
    def exposed_train(self, classes, trainloc, validloc):
        model = server.fmodel
        train_batches = ImageDataGenerator().flow_from_directory(trainloc, target_size=(224,224), classes=classes, batch_size=10)
        valid_batches = ImageDataGenerator().flow_from_directory(validloc, target_size=(224,224), classes=classes, batch_size=4)
        model.fit_generator(train_batches, steps_per_epoch=1,validation_data=valid_batches, validation_steps=1, epochs=30, verbose=2)
        server.fmodel = model
        return True
        
#model = buildModel(train_path, valid_path, ['dog','cat','monkey','cow'])


if __name__ == "__main__":
    # Now time to start the server
    server = ThreadedServer(ClassifierService, port = 12345)
    # Attach model to server
    t = Thread(target = server.start)
    t.daemon = True
    t.start()
    t.join()
```
Lines in question

**Comment by ControlCplusControlV** [comment]
[CommandExecuted(agr_id='0c1eca3ba3bccae4583ca4944c7a3b3c9fc286dc0bd8687f04bd47f54bb8e01b', script_id='3', cmd_idx=0, command={'run': {'entry_point': '/bin/ls', 'args': ('/golem/work/dataset',), 'capture': {'stdout': {'stream': {}}, 'stderr': {'stream': {}}}}}, success=True, message=None, stdout='test\ntrain\nvalid\n', stderr=None)]
instances: [('q53.b2', 'starting')]
Service Running
[2021-07-31T08:11:02.362-0700 WARNING yapapi.services] Unhandled exception in service
Traceback (most recent call last):
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/services.py", line 469, in _run_instance
    batch = batch_task.result()
  File "/home/controlc/Downloads/gimg5/requestor.py", line 67, in run
    built = yield self._ctx.commit()
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/services.py", line 478, in _run_instance
    fut_result = yield batch
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/engine.py", line 556, in process_batches
    results = await get_batch_results()
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/engine.py", line 542, in get_batch_results
    raise CommandExecutionError(evt.command, evt.message, evt.stderr)
yapapi.rest.activity.CommandExecutionError: Command '{'run': {'entry_point': '/golem/run/ClassifierClient.py', 'args': ('-t', '/golem/work/dataset/train', '-v', '/golem/work/dataset/valid', '--start', '-c', 'dog', 'cat', 'monkey', 'cow'), 'capture': {'stdout': {'stream': {}}, 'stderr': {'stream': {}}}}}' failed on provider; message: 'ExeScript command exited with code 1'; stderr: 'Traceback (most recent call last):
  File "/golem/run/ClassifierClient.py", line 6, in <module>
    conn = rpyc.connect("localhost", 12345)
  File "/usr/local/lib/python3.8/site-packages/rpyc/utils/factory.py", line 98, in connect
    s = SocketStream.connect(host, port, ipv6=ipv6, keepalive=keepalive)
  File "/usr/local/lib/python3.8/site-packages/rpyc/core/stream.py", line 173, in connect
    return cls(cls._connect(host, port, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/rpyc/core/stream.py", line 123, in _connect
    family, socktype, proto, _, sockaddr = socket.getaddrinfo(host, port, family,
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
'
