### ISSUE TITLE
/model/ model folder not found 

### ISSUE THREAD

**Issue by ControlCplusControlV** [ControlCplusControlV/Golem-Image-Classifier#7]
Model folder is on volume,  path is correct and files are there, after all it works on docker, so it must be some permssions issue, not sure how to fix
```Traceback (most recent call last):
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/services.py", line 469, in _run_instance
    batch = batch_task.result()
  File "/home/controlc/Downloads/gimg4/requestor.py", line 48, in start
    yield self._ctx.commit()
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/services.py", line 478, in _run_instance
    fut_result = yield batch
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/engine.py", line 556, in process_batches
    results = await get_batch_results()
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/engine.py", line 542, in get_batch_results
    raise CommandExecutionError(evt.command, evt.message, evt.stderr)
yapapi.rest.activity.CommandExecutionError: Command '{'run': {'entry_point': '/golem/run/imageclassifier.py', 'args': ('--predict', '/golem/work/data/test', '--batch', '1'), 'capture': {'stdout': {'stream': {}}, 'stderr': {'stream': {}}}}}' failed on provider; message: 'ExeScript command exited with code 1'; stderr: '2021-07-13 03:14:24.576198: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-07-13 03:14:24.576234: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/golem/run/imageclassifier.py", line 53, in <module>
    predict(args.predict, int(args.batch))
  File "/golem/run/imageclassifier.py", line 31, in predict
    model = keras.models.load_model("/golem/work/model")
  File "/usr/local/lib/python3.8/site-packages/keras/saving/save.py", line 206, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/usr/local/lib/python3.8/site-packages/keras/saving/saved_model/load.py", line 109, in load
    meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: /golem/work/model/{saved_model.pbtxt|saved_model.pb}
```

**Comment by ControlCplusControlV** [comment]
The model folder in this repo isn't complete because of Github file limitations which is important to note

**Comment by ControlCplusControlV** [comment]
https://mega.nz/folder/g6AUADaL#ygTd_qMgJkEKuCVu4btO0Q

**Comment by ControlCplusControlV** [comment]
98496b9d38c24a85e46cb081237c08e460224777925b2ade6ae3075d

**Comment by ControlCplusControlV** [comment]
cd62cbd4aa54d111abf29d09cb229d7d488bd18a03b8b16da28a53f7

**Comment by ControlCplusControlV** [comment]
4cb97b8b0961fdf2a1953821b183fa9bc7fe1eadbf068cee99eb6249 - should have model folder structure correct

**Comment by ControlCplusControlV** [comment]
[simple-service-yapapi-2021-07-16_14.25.06.log](https://github.com/ControlCplusControlV/Golem-Image-Classifier/files/6833498/simple-service-yapapi-2021-07-16_14.25.06.log)

**Comment by ControlCplusControlV** [comment]
Requestor Script Used
```#!/usr/bin/env python3
"""
the requestor agent controlling and interacting with Image Classifier
"""
import asyncio
from datetime import datetime, timedelta, timezone
import pathlib
import random
import string
import sys

import argparse
from yapapi import (
    NoPaymentAccountError,
    __version__ as yapapi_version,
    windows_event_loop_fix,
)
from yapapi import Golem
from yapapi.services import Service, ServiceState

from yapapi.log import enable_default_logger, pluralize
from yapapi.payload import vm


NUM_INSTANCES = 1
STARTING_TIMEOUT = timedelta(minutes=100)


class ImageClassifierService(Service):
    CLASSIFIER = "/golem/work/imageclassifier.py"

    @staticmethod
    async def get_payload():
        return await vm.repo(
            image_hash="4cb97b8b0961fdf2a1953821b183fa9bc7fe1eadbf068cee99eb6249",
            min_mem_gib=5,
            min_storage_gib=7,
        )

    async def start(self):
        """
        Setup the volume so that it will play nice with the classifier and all the needed data
        is stored there. Send over the model, and make the needed dirs 
        """
        
        status = self._ctx.send_file("model.tar.gz", "/golem/work/model.tar.gz")
        status = yield self._ctx.commit()
        transfer = await status
        print("Model Transferred")
        self._ctx.run("/bin/tar", "-xzvf", "/golem/work/model.tar.gz")
        yield self._ctx.commit()
        self._ctx.run("/bin/ls", "/golem/work/")
        files = yield self._ctx.commit()
        rfiles = await files
        print(rfiles)
        
    async def run(self):
        while True:
            task = input("What task do you wish to run? [predict/train] : ")
            if task == "predict":
                    imagepath = input("What is the name of the image you wish to identify : ")
                    await asyncio.sleep(10)
                    self._ctx.send_file(str(imagepath), str(f"/golem/work/dataset/test/"))
                    print("Test Image Sent!")
                    self._ctx.run(self.CLASSIFIER, "--predict", "/golem/work/dataset/test", "--batch", "1")
                    future_results = yield self._ctx.commit()
                    results = await future_results
                    print(results)
            elif task == "train":
                    datapath = input("What is the name of the training data folder :")
                    self._ctx.send_file(str(datapath), str("/golem/work/dataset/train"))
                    self._ctx.run(self.CLASSIFIER, "--trainloc", "/golem/work/dataset/train") 
                    future_results = yield self._ctx.commit()
                    results = await future_results
                    print(results)
                    print("Model Successfully Trained")

async def main(subnet_tag, driver=None, network=None):
    async with Golem(
        budget=1.00,
        subnet_tag=subnet_tag,
        driver=driver,
        network=network,
    ) as golem:

        print(
            f"yapapi version: {yapapi_version}\n"
            f"Using subnet: {subnet_tag}, "
            f"payment driver: {golem.driver}, "
            f"and network: {golem.network}\n"
        )

        commissioning_time = datetime.now()

        print(
            f"starting {pluralize(NUM_INSTANCES, 'instance')}"
        )

        # start the service

        cluster = await golem.run_service(
            ImageClassifierService,
            num_instances=NUM_INSTANCES,
            expiration=datetime.now(timezone.utc) + timedelta(minutes=120),
        )

        # helper functions to display / filter instances

        def instances():
            return [(s.provider_name, s.state.value) for s in cluster.instances]

        def still_running():
            return any([s for s in cluster.instances if s.is_available])

        def still_starting():
            return len(cluster.instances) < NUM_INSTANCES or any(
                [s for s in cluster.instances if s.state == ServiceState.starting]
            )

        # wait until instances are started

        while still_starting() and datetime.now() < commissioning_time + STARTING_TIMEOUT:
            print(f"instances: {instances()}")
            await asyncio.sleep(5)

        if still_starting():
            raise Exception(f"Failed to start instances before {STARTING_TIMEOUT} elapsed :( ...")

        print("All instances started :)")

        # allow the service to run for a short while
        # (and allowing its requestor-end handlers to interact with it)

        start_time = datetime.now()

        while datetime.now() < start_time + timedelta(minutes=2):
            print(f"instances: {instances()}")
            await asyncio.sleep(5)

        print(f"stopping instances")
        cluster.stop()

        # wait for instances to stop

        cnt = 0
        while cnt < 10 and still_running():
            print(f"instances: {instances()}")
            await asyncio.sleep(5)

    print(f"instances: {instances()}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    now = datetime.now().strftime("%Y-%m-%d_%H.%M.%S")
    parser.set_defaults(log_file=f"simple-service-yapapi-{now}.log")
    args = parser.parse_args()

    # This is only required when running on Windows with Python prior to 3.8:
    windows_event_loop_fix()

    enable_default_logger(
        log_file=args.log_file,
        debug_activity_api=True,
        debug_market_api=True,
        debug_payment_api=True,
    )

    loop = asyncio.get_event_loop()
    task = loop.create_task(
        main(subnet_tag="devnet-beta.2", driver="zksync", network="rinkeby")
    )

    try:
        loop.run_until_complete(task)
    except NoPaymentAccountError as e:
        handbook_url = (
            "https://handbook.golem.network/requestor-tutorials/"
            "flash-tutorial-of-requestor-development"
        )
        print(
            f""
            f"No payment account initialized for driver `{e.required_driver}` "
            f"and network `{e.required_network}`.\n\n"
            f"See {handbook_url} on how to initialize payment accounts for a requestor node."
            f""
        )
    except KeyboardInterrupt:
        print(
            f""
            "Shutting down gracefully, please wait a short while "
            "or press Ctrl+C to exit immediately..."
            f""
        )
        task.cancel()
        try:
            loop.run_until_complete(task)
            print(
                f"Shutdown completed, thank you for waiting!"
            )
        except (asyncio.CancelledError, KeyboardInterrupt):
            pass```

**Comment by ControlCplusControlV** [comment]
Model Transferred
instances: [('jiuzhang.b2', 'starting')]
instances: [('jiuzhang.b2', 'starting')]
[2021-07-16T14:34:52.277-0700 WARNING yapapi.services] Unhandled exception in service
Traceback (most recent call last):
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/services.py", line 469, in _run_instance
    batch = batch_task.result()
  File "/home/controlc/Downloads/gimg4/request.py", line 51, in start
    yield self._ctx.commit()
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/services.py", line 478, in _run_instance
    fut_result = yield batch
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/engine.py", line 556, in process_batches
    results = await get_batch_results()
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/engine.py", line 542, in get_batch_results
    raise CommandExecutionError(evt.command, evt.message, evt.stderr)
yapapi.rest.activity.CommandExecutionError: Command '{'run': {'entry_point': '/bin/tar', 'args': ('-xzvf', '/golem/work/model.tar.gz'), 'capture': {'stdout': {'stream': {}}, 'stderr': {'stream': {}}}}}' failed on provider; message: 'ExeScript command exited with code 2'; stderr: 'tar: model/variables/variables.data-00000-of-00001: Wrote only 512 of 10240 bytes
tar: model/variables/variables.index: Cannot write: No space left on device
tar: model/keras_metadata.pb: Cannot write: No space left on device
tar: Exiting with failure status due to previous errors
'

**Comment by ControlCplusControlV** [comment]
Model Transferred
instances: [('jiuzhang.b2', 'starting')]
instances: [('jiuzhang.b2', 'starting')]
[2021-07-16T15:55:16.417-0700 WARNING yapapi.services] Unhandled exception in service
Traceback (most recent call last):
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/services.py", line 469, in _run_instance
    batch = batch_task.result()
  File "/home/controlc/Downloads/gimg4/request.py", line 51, in start
    yield self._ctx.commit()
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/services.py", line 478, in _run_instance
    fut_result = yield batch
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/engine.py", line 556, in process_batches
    results = await get_batch_results()
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/engine.py", line 542, in get_batch_results
    raise CommandExecutionError(evt.command, evt.message, evt.stderr)
yapapi.rest.activity.CommandExecutionError: Command '{'run': {'entry_point': '/bin/tar', 'args': ('-xzvf', '/golem/work/model.tar.gz', '-C', '/golem/work/'), 'capture': {'stdout': {'stream': {}}, 'stderr': {'stream': {}}}}}' failed on provider; message: 'ExeScript command exited with code 2'; stderr: 'tar: model/saved_model.pb: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: model/variables/variables.data-00000-of-00001: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: model/variables/variables.index: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: model/variables: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: model/keras_metadata.pb: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: model: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: Exiting with failure status due to previous errors

**Comment by ControlCplusControlV** [comment]
self._ctx.run("/bin/tar", "-xzvf", "/golem/work/model.tar.gz", "-C", "/golem/work/")

**Comment by ControlCplusControlV** [comment]
194a3446c79d2b7ded8a2aadf87256411b68a4a86ce6af30ac9d32cc new test hash

**Comment by ControlCplusControlV** [comment]
`    async def start(self):
        """
        Setup the volume so that it will play nice with the classifier and all the needed data
        is stored there. Send over the model, and make the needed dirs 
        """
        
        status = self._ctx.send_file("model.tar.gz", "/golem/work/model.tar.gz")
        status = yield self._ctx.commit()
        transfer = await status
        print("Model Transferred")
        self._ctx.run("/bin/tar","--no-same-owner", "-C", "/golem/work/", "-xzvf", "/golem/work/model.tar.gz")
        zipped = yield self._ctx.commit()
        finalized = await zipped
        self._ctx.run("/bin/ls", "/golem/work/model")
        files = yield self._ctx.commit()
        rfiles = await files
        print(rfiles)`

**Comment by ControlCplusControlV** [comment]
#!/usr/bin/env python3
"""
the requestor agent controlling and interacting with Image Classifier
"""
import asyncio
from datetime import datetime, timedelta, timezone
import pathlib
import random
import string
import sys

import argparse
from yapapi import (
    NoPaymentAccountError,
    __version__ as yapapi_version,
    windows_event_loop_fix,
)
from yapapi import Golem
from yapapi.services import Service, ServiceState

from yapapi.log import enable_default_logger, pluralize
from yapapi.payload import vm


NUM_INSTANCES = 1
STARTING_TIMEOUT = timedelta(minutes=100)


class ImageClassifierService(Service):
    CLASSIFIER = "/golem/run/imageclassifier.py"

    @staticmethod
    async def get_payload():
        return await vm.repo(
            image_hash="194a3446c79d2b7ded8a2aadf87256411b68a4a86ce6af30ac9d32cc",
            min_mem_gib=8,
            min_storage_gib=20,
        )

    async def start(self):
        """
        Setup the volume so that it will play nice with the classifier and all the needed data
        is stored there. Send over the model, and make the needed dirs 
        """
        
        status = self._ctx.send_file("model.tar.gz", "/golem/work/model.tar.gz")
        status = yield self._ctx.commit()
        transfer = await status
        print("Model Transferred")
        self._ctx.run("/bin/tar","--no-same-owner", "-C", "/golem/work/", "-xzvf", "/golem/work/model.tar.gz")
        zipped = yield self._ctx.commit()
        finalized = await zipped
        # Next up set up some folders in the volume so the classifier can identify it
        self._ctx.run("/bin/mkdir", "/golem/work/dataset")
        dataset = yield self._ctx.commit()
        datasetf = await dataset
        self._ctx.run("/bin/mkdir", "/golem/work/dataset/test")
        test = yield self._ctx.commit()
        testf = await test
        self._ctx.run("/bin/mkdir", "/golem/work/dataset/test/Unknown")
        utest = yield self._ctx.commit()
        utestf = await utest
        self._ctx.run("/bin/ls", "/golem/work/dataset/test")
        files = yield self._ctx.commit()
        rfiles = await files
        print(rfiles)
        
    async def run(self):
        while True:
            task = input("What task do you wish to run? [predict/train] : ")
            if task == "predict":
                    imagepath = input("What is the name of the image you wish to identify : ")
                    await asyncio.sleep(10)
                    self._ctx.send_file(str(imagepath), str("/golem/work/dataset/test/Unknown/" + imagepath))
                    send = yield self._ctx.commit()
                    sendf = await send
                    print("Test Image Sent!")
                    self._ctx.run(self.CLASSIFIER, "--predict", "/golem/work/dataset/test", "--batch", "1")
                    future_results = yield self._ctx.commit()
                    results = await future_results
                    print(results)
            elif task == "train":
                    datapath = input("What is the name of the training data folder :")
                    self._ctx.send_file(str(datapath), str("/golem/work/dataset/train"))
                    self._ctx.run(self.CLASSIFIER, "--trainloc", "/golem/work/dataset/train") 
                    future_results = yield self._ctx.commit()
                    results = await future_results
                    print(results)
                    print("Model Successfully Trained")

async def main(subnet_tag, driver=None, network=None):
    async with Golem(
        budget=5.00,
        subnet_tag=subnet_tag,
        driver=driver,
        network=network,
    ) as golem:

        print(
            f"yapapi version: {yapapi_version}\n"
            f"Using subnet: {subnet_tag}, "
            f"payment driver: {golem.driver}, "
            f"and network: {golem.network}\n"
        )

        commissioning_time = datetime.now()

        print(
            f"starting {pluralize(NUM_INSTANCES, 'instance')}"
        )

        # start the service

        cluster = await golem.run_service(
            ImageClassifierService,
            num_instances=NUM_INSTANCES,
            expiration=datetime.now(timezone.utc) + timedelta(minutes=120),
        )

        # helper functions to display / filter instances

        def instances():
            return [(s.provider_name, s.state.value) for s in cluster.instances]

        def still_running():
            return any([s for s in cluster.instances if s.is_available])

        def still_starting():
            return len(cluster.instances) < NUM_INSTANCES or any(
                [s for s in cluster.instances if s.state == ServiceState.starting]
            )

        # wait until instances are started

        while still_starting() and datetime.now() < commissioning_time + STARTING_TIMEOUT:
            print(f"instances: {instances()}")
            await asyncio.sleep(5)

        if still_starting():
            raise Exception(f"Failed to start instances before {STARTING_TIMEOUT} elapsed :( ...")

        print("All instances started :)")

        # allow the service to run for a short while
        # (and allowing its requestor-end handlers to interact with it)

        start_time = datetime.now()

        while datetime.now() < start_time + timedelta(minutes=2):
            print(f"instances: {instances()}")
            await asyncio.sleep(5)

        print(f"stopping instances")
        cluster.stop()

        # wait for instances to stop

        cnt = 0
        while cnt < 10 and still_running():
            print(f"instances: {instances()}")
            await asyncio.sleep(5)

    print(f"instances: {instances()}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    now = datetime.now().strftime("%Y-%m-%d_%H.%M.%S")
    parser.set_defaults(log_file=f"simple-service-yapapi-{now}.log")
    args = parser.parse_args()

    # This is only required when running on Windows with Python prior to 3.8:
    windows_event_loop_fix()

    enable_default_logger(
        log_file=args.log_file,
        debug_activity_api=True,
        debug_market_api=True,
        debug_payment_api=True,
    )

    loop = asyncio.get_event_loop()
    task = loop.create_task(
        main(subnet_tag="devnet-beta.2", driver="zksync", network="rinkeby")
    )

    try:
        loop.run_until_complete(task)
    except NoPaymentAccountError as e:
        handbook_url = (
            "https://handbook.golem.network/requestor-tutorials/"
            "flash-tutorial-of-requestor-development"
        )
        print(
            f""
            f"No payment account initialized for driver `{e.required_driver}` "
            f"and network `{e.required_network}`.\n\n"
            f"See {handbook_url} on how to initialize payment accounts for a requestor node."
            f""
        )
    except KeyboardInterrupt:
        print(
            f""
            "Shutting down gracefully, please wait a short while "
            "or press Ctrl+C to exit immediately..."
            f""
        )
        task.cancel()
        try:
            loop.run_until_complete(task)
            print(
                f"Shutdown completed, thank you for waiting!"
            )
        except (asyncio.CancelledError, KeyboardInterrupt):
            pass

**Comment by ControlCplusControlV** [comment]
#!/usr/bin/env python3
"""
the requestor agent controlling and interacting with Image Classifier
"""
import asyncio
from datetime import datetime, timedelta, timezone
import pathlib
import random
import string
import sys

import argparse
from yapapi import (
    NoPaymentAccountError,
    __version__ as yapapi_version,
    windows_event_loop_fix,
)
from yapapi import Golem
from yapapi.services import Service, ServiceState

from yapapi.log import enable_default_logger, pluralize
from yapapi.payload import vm


NUM_INSTANCES = 1
STARTING_TIMEOUT = timedelta(minutes=100)


class ImageClassifierService(Service):
    CLASSIFIER = "/golem/run/imageclassifier.py"

    @staticmethod
    async def get_payload():
        return await vm.repo(
            image_hash="194a3446c79d2b7ded8a2aadf87256411b68a4a86ce6af30ac9d32cc",
            min_mem_gib=8,
            min_storage_gib=20,
        )

    async def start(self):
        """
        Setup the volume so that it will play nice with the classifier and all the needed data
        is stored there. Send over the model, and make the needed dirs 
        """
        
        status = self._ctx.send_file("model.tar.gz", "/golem/work/model.tar.gz")
        status = yield self._ctx.commit()
        transfer = await status
        print("Model Transferred")
        self._ctx.run("/bin/tar","--no-same-owner", "-C", "/golem/work/", "-xzvf", "/golem/work/model.tar.gz")
        zipped = yield self._ctx.commit()
        finalized = await zipped
        # Next up set up some folders in the volume so the classifier can identify it
        self._ctx.run("/bin/mkdir", "/golem/work/dataset")
        dataset = yield self._ctx.commit()
        datasetf = await dataset
        self._ctx.run("/bin/mkdir", "/golem/work/dataset/test")
        test = yield self._ctx.commit()
        testf = await test
        self._ctx.run("/bin/mkdir", "/golem/work/dataset/test/Unknown")
        utest = yield self._ctx.commit()
        utestf = await utest
        self._ctx.run("/bin/ls", "/golem/work/dataset/test")
        files = yield self._ctx.commit()
        rfiles = await files
        print(rfiles)
        
    async def run(self):
        while True:
            task = input("What task do you wish to run? [predict/train] : ")
            if task == "predict":
                    imagepath = input("What is the name of the image you wish to identify : ")
                    await asyncio.sleep(10)
                    self._ctx.send_file(str(imagepath), str("/golem/work/dataset/test/Unknown/" + imagepath))
                    send = yield self._ctx.commit()
                    sendf = await send
                    print("Test Image Sent!")
                    self._ctx.run(self.CLASSIFIER, "--predict", "/golem/work/dataset/test", "--batch", "1")
                    future_results = yield self._ctx.commit()
                    results = await future_results
                    print(results)
            elif task == "train":
                    datapath = input("What is the name of the training data folder :")
                    self._ctx.send_file(str(datapath), str("/golem/work/dataset/train"))
                    self._ctx.run(self.CLASSIFIER, "--trainloc", "/golem/work/dataset/train") 
                    future_results = yield self._ctx.commit()
                    results = await future_results
                    print(results)
                    print("Model Successfully Trained")

async def main(subnet_tag, driver=None, network=None):
    async with Golem(
        budget=5.00,
        subnet_tag=subnet_tag,
        driver=driver,
        network=network,
    ) as golem:

        print(
            f"yapapi version: {yapapi_version}\n"
            f"Using subnet: {subnet_tag}, "
            f"payment driver: {golem.driver}, "
            f"and network: {golem.network}\n"
        )

        commissioning_time = datetime.now()

        print(
            f"starting {pluralize(NUM_INSTANCES, 'instance')}"
        )

        # start the service

        cluster = await golem.run_service(
            ImageClassifierService,
            num_instances=NUM_INSTANCES,
            expiration=datetime.now(timezone.utc) + timedelta(minutes=120),
        )

        # helper functions to display / filter instances

        def instances():
            return [(s.provider_name, s.state.value) for s in cluster.instances]

        def still_running():
            return any([s for s in cluster.instances if s.is_available])

        def still_starting():
            return len(cluster.instances) < NUM_INSTANCES or any(
                [s for s in cluster.instances if s.state == ServiceState.starting]
            )

        # wait until instances are started

        while still_starting() and datetime.now() < commissioning_time + STARTING_TIMEOUT:
            print(f"instances: {instances()}")
            await asyncio.sleep(5)

        if still_starting():
            raise Exception(f"Failed to start instances before {STARTING_TIMEOUT} elapsed :( ...")

        print("All instances started :)")

        # allow the service to run for a short while
        # (and allowing its requestor-end handlers to interact with it)

        start_time = datetime.now()

        while datetime.now() < start_time + timedelta(minutes=2):
            print(f"instances: {instances()}")
            await asyncio.sleep(5)

        print(f"stopping instances")
        cluster.stop()

        # wait for instances to stop

        cnt = 0
        while cnt < 10 and still_running():
            print(f"instances: {instances()}")
            await asyncio.sleep(5)

    print(f"instances: {instances()}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    now = datetime.now().strftime("%Y-%m-%d_%H.%M.%S")
    parser.set_defaults(log_file=f"simple-service-yapapi-{now}.log")
    args = parser.parse_args()

    # This is only required when running on Windows with Python prior to 3.8:
    windows_event_loop_fix()

    enable_default_logger(
        log_file=args.log_file,
        debug_activity_api=True,
        debug_market_api=True,
        debug_payment_api=True,
    )

    loop = asyncio.get_event_loop()
    task = loop.create_task(
        main(subnet_tag="devnet-beta.2", driver="zksync", network="rinkeby")
    )

    try:
        loop.run_until_complete(task)
    except NoPaymentAccountError as e:
        handbook_url = (
            "https://handbook.golem.network/requestor-tutorials/"
            "flash-tutorial-of-requestor-development"
        )
        print(
            f""
            f"No payment account initialized for driver `{e.required_driver}` "
            f"and network `{e.required_network}`.\n\n"
            f"See {handbook_url} on how to initialize payment accounts for a requestor node."
            f""
        )
    except KeyboardInterrupt:
        print(
            f""
            "Shutting down gracefully, please wait a short while "
            "or press Ctrl+C to exit immediately..."
            f""
        )
        task.cancel()
        try:
            loop.run_until_complete(task)
            print(
                f"Shutdown completed, thank you for waiting!"
            )
        except (asyncio.CancelledError, KeyboardInterrupt):
            pass
